### ISSUE TITLE
Platform tracks

### ISSUE THREAD

**Issue by observingClouds** [eurec4a/eurec4a-intake#55]
As discussed in #38 the tracks of the platforms shall not be gathered in one folder but should rather be distributed in platform specific folders. Since the platform tracks are now all available on [AERIS](https://observations.ipsl.fr/thredds/catalog/EUREC4A/PRODUCTS/TRACKS/catalog.html) I wanted to make sure, that this distribution is still common sense before I create several top-level folders.

For platforms that have twins, I imagine to just create one top-level folder and have the exact identifier as a parameter. E.g. create one top-level folder SWIFT and have a `main.yaml` in there with content like

```yaml
  track:
    args:
      urlpath: https://observations.ipsl.fr/thredds/dodsC/EUREC4A/PRODUCTS/TRACKS/EUREC4A_tracks_{platform}_v1.0.nc
      auth: null
      chunks: {}
      engine: netcdf4
    driver: opendap
    description: SWIFT tracks
    metadata:
      tags:
        - track
    parameters:
      platform:
        description: specific SWIFT platform
        type: str
        default: SWIFT16
        allowed: [SWIFT16, SWIFT17, SWIFT22, SWIFT23, SWIFT24, SWIFT25]
```

Any opinions @d70-t @RobertPincus ?
